var descDB = {
'1/1': { 'desc' : 'Battery'},
'2/1': { 'desc' : 'Main headlight relay with bulb malfunction indicator'},
'2/2': { 'desc' : 'Fog light relay'},
'2/3': { 'desc' : 'Regulator, DIM-DIP'},
'2/4': { 'desc' : 'Windshield wiper intermittent relay'},
'2/5': { 'desc' : 'Seatbelt reminder/key warning relay'},
'2/7': { 'desc' : 'Central lock/delayed courtesy lighting relay'},
'2/11': { 'desc' : 'Engine cooling fan relay'},
'2/15': { 'desc' : 'Relay, exhaust temperature sensor'},
'2/16': { 'desc' : 'Tailgate wiper intermittent relay'},
'2/22': { 'desc' : 'A/C relay'},
'2/23': { 'desc' : 'Fuel pump relay'},
'2/24': { 'desc' : 'Fan relay, max.'},
'2/28': { 'desc' : 'Alarm relay'},
'2/30': { 'desc' : 'Overload relay X+'},
'2/31': { 'desc' : 'Overload relay 15+'},
'2/32': { 'desc' : 'Main relay fuel system'},
'2/42': { 'desc' : 'Combination relay ABS'},
'2/43': { 'desc' : 'Heated rear seat relay'},
'2/44': { 'desc' : 'Relay, electrically heated rear window/door mirrors'},
'2/47': { 'desc' : 'Relay, deadlock setting'},
'2/51': { 'desc' : 'Speed warning'},
'2/53': { 'desc' : 'Air pump relay'},
'2/60': { 'desc' : 'Overload relay X+'},
'3/1': { 'desc' : 'Ignition switch'},
'3/2': { 'desc' : 'Light switch'},
'3/3': { 'desc' : 'Switch, turn signal/high and low beams'},
'3/4': { 'desc' : 'Controls, cruise control'},
'3/6': { 'desc' : 'Switch, hazard lights with flasher relay'},
'3/8': { 'desc' : 'Switch, el. heated rear window/door mirrors'},
'3/9': { 'desc' : 'Brake light switch'},
'3/10': { 'desc' : 'Backup (reversing) light switch'},
'3/12': { 'desc' : 'Switch, windshield wipers and washer'},
'3/13': { 'desc' : 'Switch, tailgate washer and wiper'},
'3/25': { 'desc' : 'Switch, power sunroof'},
'3/37': { 'desc' : 'Horn connectors'},
'3/38': { 'desc' : 'Contact, brake pedal'},
'3/39': { 'desc' : 'Contact, dutch pedal'},
'3/47': { 'desc' : 'Handbrake switch'},
'3/54': { 'desc' : 'REG and A/C switch'},
'3/55': { 'desc' : 'A/C panel lights'},
'3/56': { 'desc' : 'Heater fan switch'},
'3/57': { 'desc' : 'Climate control'},
'3/58': { 'desc' : 'Switch, rear fog light'},
'3/59': { 'desc' : 'Beam width control'},
'3/61': { 'desc' : 'Controls, trip computer'},
'3/62': { 'desc' : 'Alarm switch, hood'},
'3/63': { 'desc' : 'Program selector, automatic transmission'},
'3/64': { 'desc' : 'Switch for heated rear seat, left side'},
'3/69': { 'desc' : 'Switch for heated rear seat, right side'},
'3/71': { 'desc' : 'Transmission range selector indicator'},
'3/72': { 'desc' : 'Kick-down switch on throttle controls'},
'3/74': { 'desc' : 'Lock, left front'},
'3/75': { 'desc' : 'Lock, right front'},
'3/76': { 'desc' : 'Lock, left rear'},
'3/77': { 'desc' : 'Lock, right rear'},
'3/78': { 'desc' : 'Lock tailgate'},
'3/85': { 'desc' : 'Power window switch, left rear door'},
'3/86': { 'desc' : 'Power window switch, right rear door'},
'3/87': { 'desc' : 'Switch, power door mirror, left side'},
'3/88': { 'desc' : 'Switch, power door mirror, right side'},
'3/89': { 'desc' : 'Control module, left seat'},
'3/91': { 'desc' : 'Switch, heated left seat'},
'3/92': { 'desc' : 'Switch, heater right seat'},
'3/93': { 'desc' : 'Seat belt lock, left seat'},
'3/94': { 'desc' : 'Seat belt lock, right seat'},
'3/95': { 'desc' : 'Switch, TRACS'},
'3/97': { 'desc' : 'Switch, auto-down relay, power window'},
'3/99': { 'desc' : 'Front fog light switch'},
'4/3': { 'desc' : 'Control module, cruise control'},
'4/4': { 'desc' : 'Rheostat'},
'4/5': { 'desc' : 'Safety drcuit SRS'},
'4/9': { 'desc' : 'SRS sensor module'},
'4/10': { 'desc' : 'Control module EZK (Dl) ignition system'},
'4/15': { 'desc' : 'Di power stage and ignition coil'},
'4/16': { 'desc' : 'ABS control module'},
'7/54': { 'desc' : 'Throttle position (TP) sensor'},
'7/55': { 'desc' : 'Thermoelement, 3-way catalytic converter (TWC)'},
'7/56': { 'desc' : 'Sensor ABS left rear'},
'7/57': { 'desc' : 'Sensor ABS right rear'},
'7/58': { 'desc' : 'Pedal sensor ABS'},
'7/59': { 'desc' : 'Temperature sensor, left duct'},
'7/60': { 'desc' : 'Temperature sensor, right duct'},
'7/64': { 'desc' : 'Cabin temperature sensor, driver\'s side'},
'7/65': { 'desc' : 'Cabin temperature sensor, passenger\'s side'},
'7/66': { 'desc' : 'Rear seat thermostat, left side'},
'7/67': { 'desc' : 'Rear seat thermostat, right side'},
'7/63': { 'desc' : 'Solar sensor ECC/\'indication LED - anti-theft alarm'},
'7/69': { 'desc' : 'Ambient temperature sensor, trip computer'},
'7/73': { 'desc' : 'Coolant level sensor'},
'7/77': { 'desc' : 'Intake air temperature sensor (IAT sensor)'},
'7/79': { 'desc' : 'Accelerometer'},
'7/81': { 'desc' : 'Pressure sensor, intake manifold'},
'7/82': { 'desc' : 'Heated oxygen sensor (HO£S) (Lambdasond), rear'},
'7/83': { 'desc' : 'High-pressure sensor, A/C'},
'8/3': { 'desc' : 'Solenoid coupling A/C'},
'8/5': { 'desc' : 'IAC idling valve'},
'8/6-10': { 'desc' : 'injectors'},
'8/15': { 'desc' : 'Hydraulic unit ABS'},
'8/17': { 'desc' : 'EGR converter'},
'8/18': { 'desc' : 'EVAP valve'},
'8/28': { 'desc' : 'Turbo control valve'},
'8/30': { 'desc' : 'Steering wheel module SRS'},
'8/31': { 'desc' : 'SRS passenger module'},
'8/33': { 'desc' : 'Igniter, left belt tensioner'},
'8/34': { 'desc' : 'Igniter, right belt tensioner'},
'8/36': { 'desc' : 'Solenoid. P-shift lock'},
'8/43': { 'desc' : 'Solenoid, aux. air intake'},
'8/45': { 'desc' : 'Solenoid, variable intake manifold'},
'9/1': { 'desc' : 'Cigarette lighter'},
'9/2': { 'desc' : 'Heated rear window'},
'9/3': { 'desc' : 'Backrest heater pad. left seat'},
'9/4': { 'desc' : 'Backrest heater pad, right seat'},
'9/5': { 'desc' : 'Seat heater pad, left seat'},
'9/6': { 'desc' : 'Seat heater pad, right seat'},
'9/8': { 'desc' : 'Seat heater pad. left rear seat'},
'9/9': { 'desc' : 'Backrest heater pad, left rear seat'},
'9/10': { 'desc' : 'Seat heater pad, right rear seat'},
'9/11': { 'desc' : 'Backrest heater pad, right rear seat'},
'10/1': { 'desc' : 'Left front light'},
'10/2': { 'desc' : 'Right front light'},
'10/5': { 'desc' : 'Left front fog light assy.'},
'10/6': { 'desc' : 'Right front fog light assy.'},
'10/9': { 'desc' : 'Left parking light and turn signal, front'},
'10/10': { 'desc' : 'Right parking light and turn signal, front'},
'10/11': { 'desc' : 'Left parking light, front'},
'10/12': { 'desc' : 'Right parking light, front'},
'10/13': { 'desc' : 'Left turn signal, front'},
'10/14': { 'desc' : 'Right turn signal, front'},
'10/15': { 'desc' : 'Left side indicator light'},
'10/16': { 'desc' : 'Right side indicator light'},
'10/17': { 'desc' : 'Right tail light'},
'10/18': { 'desc' : 'Left tail light'},
'10/19': { 'desc' : 'High-level brake light'},
'10/20': { 'desc' : 'License plate light'},
'10/22': { 'desc' : 'Inside light, ceiling'},
'10/24': { 'desc' : 'Trunk lighting'},
'10/26': { 'desc' : 'Reading light, left rear'},
'10/27': { 'desc' : 'Reading light, right rear'},
'10/29': { 'desc' : 'Glove box lighting'},
'10/30': { 'desc' : 'Warning lamp, left front door'},
'10/31': { 'desc' : 'Warning lamp, right front door'},
'10/32': { 'desc' : 'Warning lamp, left rear door'},
'10/33': { 'desc' : 'Warning lamp, right rear door'},
'10/37': { 'desc' : 'Cigarette lighter illumination'},
'10/40': { 'desc' : 'Gear selector light'},
'10/43': { 'desc' : 'Right brake light'},
'10/44': { 'desc' : 'Right parking light, rear'},
'10/45': { 'desc' : 'Right parking/tail light'},
'10/46': { 'desc' : 'Right rear fog light'},
'10/47': { 'desc' : 'Lamp, right turn signal, rear'},
'10/48': { 'desc' : 'Right back-up light'},
'10/50': { 'desc' : 'Left brake light'},
'10/51': { 'desc' : 'Left parking light rear'},
'10/52': { 'desc' : 'Lett parking/tai! light'},
'10/53': { 'desc' : 'Lett rear fog tight'},
'4/19': { 'desc' : 'Remote control module, central lock/anti-theft alarm'},
'4/28': { 'desc' : 'Control module, AW 50-42 automatic transmission'},
'4/29': { 'desc' : 'Control module, left seat'},
'4/30': { 'desc' : 'Control module, ECC'},
'4/31': { 'desc' : 'Power module, heater fan'},
'4/33': { 'desc' : 'Control module, power sunroof'},
'4/34': { 'desc' : 'Voltage regulator, 8 volts'},
'4/35': { 'desc' : 'Voltage regulator, 5 volts'},
'4/36': { 'desc' : 'Combined instrument microprocessor'},
'4/37': { 'desc' : 'Control module, right seat'},
'4/41': { 'desc' : 'Control module, Fenix 5.2 MFI'},
'4/44': { 'desc' : 'D! power stage and ignition coil'},
'4/45': { 'desc' : 'Control module. LH 3.2 MFI'},
'4/46': { 'desc' : 'Control module, Motronic 4,3 MFI'},
'4/47': { 'desc' : 'Ignition coil, Fenix 5.2 MFI'},
'4/48': { 'desc' : 'Ignition power stage, Fenix 5.2 MFI'},
'5/1': { 'desc' : 'Combined instrument'},
'5/2': { 'desc' : 'Clock module'},
'5/3': { 'desc' : 'Ambient temperature/dock module'},
'5/4': { 'desc' : 'Trip computer'},
'6/1': { 'desc' : 'Windshield wiper motor'},
'6/2': { 'desc' : 'Washer motor front'},
'6/3': { 'desc' : 'Right headlight wiper motor'},
'6/4': { 'desc' : 'Left headlight wiper motor'},
'6/15': { 'desc' : 'Power sunroof motor'},
'6/24': { 'desc' : 'Cruise control vacuum pump'},
'6/25': { 'desc' : 'Starter motor'},
'6/26': { 'desc' : 'Generator'},
'6/28': { 'desc' : 'Heater fan'},
'6/29': { 'desc' : 'Engine cooling fan'},
'6/30': { 'desc' : 'Tailgate washer motor'},
'6/31': { 'desc' : 'Fuel pump'},
'6/32': { 'desc' : 'Tailgate wiper motor'},
'6/33': { 'desc' : 'Fuel level sensor'},
'6/34': { 'desc' : 'Power antenna'},
'6/35': { 'desc' : 'Parking heater'},
'6/37': { 'desc' : 'Central lock motor, tank cap'},
'6/38': { 'desc' : 'Beam width control, left actuator'},
'6/39': { 'desc' : 'Beam width control, right actuator'},
'6/45': { 'desc' : 'Servo motor, temperature shutter, driver\'s side'},
'6/46': { 'desc' : 'Servo motor, temperature shutter, passenger\'s side'},
'6/47': { 'desc' : 'Servo motor, floor and defroster shutter'},
'6/48': { 'desc' : 'Servo motor, recirculation shutter'},
'6/49': { 'desc' : 'Servo motor, ventilation shutter'},
'6/50': { 'desc' : 'Motor, left seat backrest'},
'6/51': { 'desc' : 'Motor, up/down front edge of left seat'},
'6/52': { 'desc' : 'Motor, up/down rear edge of left seat'},
'6/53': { 'desc' : 'Motor, fore/aft left seat'},
'6/54': { 'desc' : 'Air pump'},
'6/58': { 'desc' : 'Power window motor, left front door'},
'6/59': { 'desc' : 'Power window motor, left rear door'},
'6/60': { 'desc' : 'Power window motor, right front door'},
'6/61': { 'desc' : 'Power window motor, right rear door'},
'6/62': { 'desc' : 'Power door mirror, left side'},
'6/63': { 'desc' : 'Power door mirror, right side'},
'7/1': { 'desc' : 'Bulb malfunction indicator, rear'},
'7/4': { 'desc' : 'Brake fluid level sensor'},
'7/5': { 'desc' : 'Washer fluid level sensor'},
'7/6': { 'desc' : 'Oil pressure sensor'},
'7/11': { 'desc' : 'Ambient temperature sensor. ECC'},
'7/15': { 'desc' : 'Heated oxygen sensor (H02S) (Lambdasond), front'},
'7/16': { 'desc' : 'Engine temperature sensor'},
'7/17': { 'desc' : 'Mass air tlow (MAF) sensor'},
'7/21': { 'desc' : 'Camshaft position sensor (CMP)'},
'7/23': { 'desc' : 'Knock sensor (KS), rear'},
'7/24': { 'desc' : 'Knock sensor (KS), front'},
'7/25': { 'desc' : 'Pulse sensor'},
'7/31': { 'desc' : 'ABS sensor, left front'},
'7/32': { 'desc' : 'ABS sensor, right front'},
'7/33': { 'desc' : 'Speedometer sensor'},
'7/37': { 'desc' : 'Temperature sensor, EGR'},
'7/43': { 'desc' : 'Thermostat, left seat'},
'7/44': { 'desc' : 'Thermostat, right seat'},
'7/47': { 'desc' : 'PTC resistor, pre-heater'},
'7/50': { 'desc' : 'A/C pressure sensor'},
'7/53': { 'desc' : 'Pressostat, A/C'},
'10/54': { 'desc' : 'Lamp, left turn signal, rear'},
'10/55': { 'desc' : 'Left back-up light'},
'10/64': { 'desc' : 'Right high beam'},
'10/66': { 'desc' : 'Right low beam'},
'10/68': { 'desc' : 'Left high beam'},
'10/70': { 'desc' : 'Left tow beam'},
'10/72': { 'desc' : 'Ashtray lighting, front'},
'10/74': { 'desc' : 'Indicator lamp, exhaust gas temperature'},
'10/77': { 'desc' : 'Indicator lamp, SRS'},
'10/79': { 'desc' : 'Indicator lamp, winter program and low gear  (automatic transmission)'},
'10/82': { 'desc' : 'Indicator lamp, ABS'},
'10/83': { 'desc' : 'Indicator lamp, hand brake'},
'10/84': { 'desc' : 'Brake warning lamp'},
'10/85': { 'desc' : 'Warning light, high beam'},
'10/86': { 'desc' : 'Oil pressure warning lamp'},
'10/87': { 'desc' : 'Indicator lamp, charging'},
'10/88': { 'desc' : 'Indicator light, bulb malfunction indicator'},
'10/89': { 'desc' : 'Indicator lamp, rear fog lights'},
'10/90': { 'desc' : 'Washer level warning lamp'},
'10/91': { 'desc' : 'Service reminder indicator'},
'10/94': { 'desc' : 'Indicator lamp, right turn signal'},
'10/95': { 'desc' : 'Indicator lamp, left turn signal'},
'10/96': { 'desc' : 'Instrument lighting'},
'10/97': { 'desc' : 'Entry lighting, driver\'s side'},
'10/98': { 'desc' : 'Ashtray lighting, rear'},
'10/102': { 'desc' : 'Entry lighting, passenger side'},
'10/105': { 'desc' : 'Fuel level warning lamp'},
'10/106': { 'desc' : 'Check engine (malfunction indicator lamp) warning lamp'},
'10/107': { 'desc' : 'Indicator lamp, TRACS'},
'10/108': { 'desc' : 'Extra brake light, spoiler'},
'10/109': { 'desc' : 'Indicator lamp, trailer'},
'10/110': { 'desc' : 'Coolant level warning lamp'},
'10/113': { 'desc' : 'Alarm warning LED'},
'10/114': { 'desc' : 'Vanity mirror lighting, left side'},
'10/115': { 'desc' : 'Vanity mirror lighting, right side'},
'11/1': { 'desc' : 'Fuses'},
'11/2': { 'desc' : 'Fuses'},
'11/3': { 'desc' : 'Fuses'},
'11/4': { 'desc' : 'Fuses'},
'11/5': { 'desc' : 'Fuses'},
'11/6': { 'desc' : 'Fuses'},
'11/7': { 'desc' : 'Fuses'},
'11/8': { 'desc' : 'Fuses'},
'11/9': { 'desc' : 'Fuses'},
'11/10': { 'desc' : 'Fuses'},
'11/11': { 'desc' : 'Fuses'},
'11/12': { 'desc' : 'Fuses'},
'11/13': { 'desc' : 'Fuses'},
'11/14': { 'desc' : 'Fuses'},
'11/15': { 'desc' : 'Fuses'},
'11/16': { 'desc' : 'Fuses'},
'11/17': { 'desc' : 'Fuses'},
'11/18': { 'desc' : 'Fuses'},
'11/19': { 'desc' : 'Fuses'},
'11/20': { 'desc' : 'Fuses'},
'11/21': { 'desc' : 'Fuses'},
'11/22': { 'desc' : 'Fuses'},
'11/23': { 'desc' : 'Fuses'},
'11/24': { 'desc' : 'Fuses'},
'11/25': { 'desc' : 'Fuses'},
'11/26': { 'desc' : 'Fuses'},
'11/27': { 'desc' : 'Fuses'},
'11/28': { 'desc' : 'Fuses'},
'11/29': { 'desc' : 'Fuses'},
'11/30': { 'desc' : 'Fuses'},
'11/31': { 'desc' : 'Fuses'},
'11/32': { 'desc' : 'Fuses'},
'11/33': { 'desc' : 'Fuses'},
'11/34': { 'desc' : 'Fuses'},
'11/35': { 'desc' : 'Fuses'},
'11/36': { 'desc' : 'Fuses'},
'11/37': { 'desc' : 'Fuses'},
'11/38': { 'desc' : 'Fuses'},
'11/39': { 'desc' : 'Fuses'},
'11/40': { 'desc' : 'Fuses'},
'15/2': { 'desc' : '30 rail in central electrical unit'},
'15/4': { 'desc' : '151 rail in central electrical unit'},
'15/8': { 'desc' : 'X rail in central electrical unit'},
'16/1': { 'desc' : 'Radio'},
'16/3': { 'desc' : 'Loudspeaker right front door'},
'16/4': { 'desc' : 'Loudspeaker left front door'},
'16/5': { 'desc' : 'Loudspeaker right rear door'},
'16/6': { 'desc' : 'Loudspeaker left rear door'},
'16/7': { 'desc' : 'Loudspeaker, instrument panel, right side'},
'16/8': { 'desc' : 'Loudspeaker, instrument panel, left side'},
'16/9': { 'desc' : 'Antenna'},
'16/10': { 'desc' : 'Horn 1'},
'16/11': { 'desc' : 'Horn 2'},
'16/16': { 'desc' : 'Antenna booster'},
'16/17': { 'desc' : 'Loudspeaker, rear shelf/D-post, left side'},
'16/18': { 'desc' : 'Loudspeaker, rear shelf/D-post, right side'},
'16/19': { 'desc' : 'Alarm signal'},
'17/1': { 'desc' : 'Service socket for starter motor'},
'17/7': { 'desc' : 'OBD (Diagnostic) socket A'},
'17/10': { 'desc' : 'OBD (Diagnostic) socket B'},
'17/13': { 'desc' : 'OBDIl (Diagnostic) socket'},
'18/4': { 'desc' : 'Contact reel, SRS'},
'19/1': { 'desc' : 'Temperature gauge'},
'19/2': { 'desc' : 'Tachometer'},
'19/3': { 'desc' : 'Speedometer'},
'19/5': { 'desc' : 'Fuel gauge'},
'19/6': { 'desc' : 'Exciter, tachometer'},
'19/7': { 'desc' : 'Exciter, speedometer, temperature gauge, fuel gauge'},
'20/2': { 'desc' : 'Distributor'},
'20/3-7': { 'desc' : 'Spark plugs'},
'20/11': { 'desc' : 'Ballast resistor'},
'20/18': { 'desc' : 'Resistor, heater fan'},
'23/0-601': { 'desc' : 'Branching points'},
'C/BA': { 'desc' : 'Connector, 2-pin, at fuel pump'},
'C/BB': { 'desc' : 'Connector, 2-pin, fuel gauge'},
'C/BC': { 'desc' : 'Connector, 4-pin, power antenna/booster'},
'C/CE': { 'desc' : 'Connector, 2-pin, heated left seat'},
'C/CF': { 'desc' : 'Connector, 2-pin, heated left seat'},
'C/CG': { 'desc' : 'Connector, 2-pin, heated right seat'},
'C/CH': { 'desc' : 'Connector, 2-pin, heated right seat'},
'C/CJ': { 'desc' : 'Connector, 6-pin, cruise control'},
'C/CK': { 'desc' : 'Connector 14-pin, power windows'},
'C/CL': { 'desc' : 'Connector, 6-pin, tailgate wash/wipe'},
'C/CM': { 'desc' : 'Connector, 2-pin, heated rear seat, left side'},
'C/CN': { 'desc' : 'Connector, 2-pin, heated rear seat, left side'},
'C/CP': { 'desc' : 'Connector, 2-pin, heated rear seat, right side'},
'C/CQ': { 'desc' : 'Connector, 2-pin, heated rear seat, right side'},
'C/CR': { 'desc' : '14-pin connector, audio'},
'c/cs': { 'desc' : '10-pin connector, audio'},
'C/EA': { 'desc' : 'Connector, 1 -pin, engine cooling fan'},
'C/EB': { 'desc' : 'Connector, 4-pin, high pressure sensor, A/C'},
'C/EC': { 'desc' : 'Connector, 1-pin, solenoid switch A/C'},
'C/ED': { 'desc' : 'Connector. 15-pin, ABS'},
'C/EG': { 'desc' : '2-pin connector, engine coolant temperature sensor'},
'C/EH': { 'desc' : 'Connector, 3-pin, camshaft position sensor (CMP)'},
'C/EJ': { 'desc' : 'Connector, 2-pin, impulse sensor'},
'C/EK': { 'desc' : 'Connector. 2-pin. windshield wiper motor'},
'C/EL': { 'desc' : 'Connector. 3-pin, windshield wiper motor'},
'C/EM': { 'desc' : 'Connector, 2-pin at tunnel'},
'C/EN': { 'desc' : 'Connector. 2-pin, EGR temp, sensor'},
'C/EP': { 'desc' : 'Connector, 4-pin, heated oxygen sensor (H02S)(Lambdasond), front'},
'C/EQ': { 'desc' : 'Connector, 4-pin, heated oxygen sensor (H02S)(Lambdasond), rear'},
'K/1': { 'desc' : 'Relay, auto-down power window'},
'24/1': { 'desc' : 'Connector, 14-pin Instrument pane! harness - Firewall harness'},
'24/2': { 'desc' : 'Connector, 53-pin Engine compartment harness - Firewall harness'},
'24/3': { 'desc' : 'LHD cars:Connector, pos. 26-53 in 53-pin RHD cars:Connector, 53-pin Firewall harness - Door sill harness, left'},
'24/4': { 'desc' : 'Connector, pos. 1-37 in 53-pin'},
'24/5': { 'desc' : 'Connector, 24-pin'},
'24/6': { 'desc' : 'Connector, 24-pin'},
'24/7': { 'desc' : 'Connector, 14-pin'},
'24/9': { 'desc' : 'Connector, 4-pin'},
'24/10': { 'desc' : 'Connector. 2-pin'},
'24/11': { 'desc' : 'Connector, 10-pin'},
'24/12': { 'desc' : 'Connector, 4-pin'},
'24/13': { 'desc' : 'Connector. 53-pin'},
'24/14': { 'desc' : 'Connector, pos. 1-25 in 53-pin'},
'24/15': { 'desc' : 'Connector, 14-pin'},
'24/16': { 'desc' : ' Connector, 26-pin Engine compartment harness - Front harness'},
'24/17 ': { 'desc' : 'Connector, 11 -pin Rocker panel (door sill) harness, left - Left rear door harness'},
'24/18 ': { 'desc' : 'Connector, 11-pin Rocker panel (door sill) harness, right - Right rear door harness'},
'24/19 ': { 'desc' : 'Connector, 4-pin Rocker panel (door sili) harness, right - Rear wheel sensor harness'},
'24/20 ': { 'desc' : 'Connector, 4-pin Firewall harness - Power sunroof harness'},
'24/21 ': { 'desc' : 'Connector, 6-pin Rocker panel (door sill) harness, left left seat'},
'24/22 ': { 'desc' : 'Connector, 6-pin Rocker panel (door sill) harness, right - right seat'},
'24/25 ': { 'desc' : 'Connector, 14-pin Rocker panel (door sill) harness, left - trunk harness'},
'24/26 ': { 'desc' : 'Connector, 2-pin Firewall harness - belt tensioner igniter harness, left side'},
'24/27 ': { 'desc' : 'Connector, 2-pin Firewall harness - belt tensioner igniter harness, right side'},
'24/29': { 'desc' : ' Connector, 2-pin at firewall'},
'24/33 ': { 'desc' : 'Connector, 2-pin Firewall harness passenger module harness'},
'24/34': { 'desc' : ' Connector pos. 38-53 in 53-pin Engine compartment harness - Firewall harness'},
'24/35A': { 'desc' : ' Connector 8-pin accessories'},
'24/35B ': { 'desc' : 'Connector 1 -pin accessories'},
'24/37 ': { 'desc' : 'Connector, 6-pin Firewall harness - switch harness heated rear seat'},
'24/42 ': { 'desc' : 'Connector, 2-pin, accessories'},
'25/9': { 'desc' : ' Front fog lights, bridge'},
'31/4': { 'desc' : 'Ground    point, engine (ground connection battery - engine)'},
'31/7': { 'desc' : 'Ground    point, A-post driver\'s side'},
'31/11': { 'desc' : 'Groond    point, trunk, left side'},
'31/12': { 'desc' : 'Ground    point, trunk, right side'},
'31/15': { 'desc' : 'Ground    point, A-post passenger\'s side'},
'31/32': { 'desc' : 'Ground point on engine (power ground)'},
'31/33': { 'desc' : '  Ground point on engine (signal ground)'},
'31/44': { 'desc' : 'Ground point, engine compartment (ground connection battery - body)'},
'31/47': { 'desc' : 'Ground    point,    left cross member'},
'31/48': { 'desc' : 'Ground    point,    right cross member'},
'31/50': { 'desc' : 'Ground    point,    central electrical unit (power    ground)'},
'31/51': { 'desc' : 'Ground    point,    central electrical unit (signal    ground)'},
'31/52': { 'desc' : 'Ground point, Dl power stage and ignition coil'},
'31/55': { 'desc' : ' Ground    point,    engine cooling fan'},
'31/65': { 'desc' : 'Ground    point,    steering column'},
'4/19': { 'desc' : 'Remote control module, central lock/anti-theft alarm'},
'4/28': { 'desc' : 'Control module, AW 50-42 automatic transmission'},
'4/29': { 'desc' : 'Control module, left seat'},
'4/30': { 'desc' : 'Control module, ECC'},
'4/31': { 'desc' : 'Power module, heater fan'},
'4/33': { 'desc' : 'Control module, power sunroof'},
'4/34': { 'desc' : 'Voltage regulator, 8 volts'},
'4/35': { 'desc' : 'Voltage regulator, 5 volts'},
'4/36': { 'desc' : 'Combined instrument microprocessor'},
'4/37': { 'desc' : 'Control module, right seat'},
'4/41': { 'desc' : 'Control module, Fenix 5.2 MFI'},
'4/44': { 'desc' : 'D! power stage and ignition coil'},
'4/45': { 'desc' : 'Control module. LH 3.2 MFI'},
'4/46': { 'desc' : 'Control module, Motronic 4,3 MFI'},
'4/47': { 'desc' : 'Ignition coil, Fenix 5.2 MFI'},
'4/48': { 'desc' : 'Ignition power stage, Fenix 5.2 MFI'},
'5/1': { 'desc' : 'Combined instrument'},
'5/2': { 'desc' : 'Clock module'},
'5/3': { 'desc' : 'Ambient temperature/dock module'},
'5/4': { 'desc' : 'Trip computer'},
'6/1': { 'desc' : 'Windshield wiper motor'},
'6/2': { 'desc' : 'Washer motor front'},
'6/3': { 'desc' : 'Right headlight wiper motor'},
'6/4': { 'desc' : 'Left headlight wiper motor'},
'6/15': { 'desc' : 'Power sunroof motor'},
'6/24': { 'desc' : 'Cruise control vacuum pump'},
'6/25': { 'desc' : 'Starter motor'},
'6/26': { 'desc' : 'Generator'},
'6/28': { 'desc' : 'Heater fan'},
'6/29': { 'desc' : 'Engine cooling fan'},
'6/30': { 'desc' : 'Tailgate washer motor'},
'6/31': { 'desc' : 'Fuel pump'},
'6/32': { 'desc' : 'Tailgate wiper motor'},
'6/33': { 'desc' : 'Fuel level sensor'},
'6/34': { 'desc' : 'Power antenna'},
'6/35': { 'desc' : 'Parking heater'},
'6/37': { 'desc' : 'Central lock motor, tank cap'},
'6/38': { 'desc' : 'Beam width control, left actuator'},
'6/39': { 'desc' : 'Beam width control, right actuator'},
'6/45': { 'desc' : 'Servo motor, temperature shutter, driver\'s side'},
'6/46': { 'desc' : 'Servo motor, temperature shutter, passenger\'s side'},
'6/47': { 'desc' : 'Servo motor, floor and defroster shutter'},
'6/48': { 'desc' : 'Servo motor, recirculation shutter'},
'6/49': { 'desc' : 'Servo motor, ventilation shutter'},
'6/50': { 'desc' : 'Motor, left seat backrest'},
'6/51': { 'desc' : 'Motor, up/down front edge of left seat'},
'6/52': { 'desc' : 'Motor, up/down rear edge of left seat'},
'6/53': { 'desc' : 'Motor, fore/aft left seat'},
'6/54': { 'desc' : 'Air pump'},
'6/58': { 'desc' : 'Power window motor, left front door'},
'6/59': { 'desc' : 'Power window motor, left rear door'},
'6/60': { 'desc' : 'Power window motor, right front door'},
'6/61': { 'desc' : 'Power window motor, right rear door'},
'6/62': { 'desc' : 'Power door mirror, left side'},
'6/63': { 'desc' : 'Power door mirror, right side'},
'7/1': { 'desc' : 'Bulb malfunction indicator, rear'},
'7/4': { 'desc' : 'Brake fluid level sensor'},
'7/5': { 'desc' : 'Washer fluid level sensor'},
'7/6': { 'desc' : 'Oil pressure sensor'},
'7/11': { 'desc' : 'Ambient temperature sensor. ECC'},
'7/15': { 'desc' : 'Heated oxygen sensor (H02S) (Lambdasond), front'},
'7/16': { 'desc' : 'Engine temperature sensor'},
'7/17': { 'desc' : 'Mass air tlow (MAF) sensor'},
'7/21': { 'desc' : 'Camshaft position sensor (CMP)'},
'7/23': { 'desc' : 'Knock sensor (KS), rear'},
'7/24': { 'desc' : 'Knock sensor (KS), front'},
'7/25': { 'desc' : 'Pulse sensor'},
'7/31': { 'desc' : 'ABS sensor, left front'},
'7/32': { 'desc' : 'ABS sensor, right front'},
'7/33': { 'desc' : 'Speedometer sensor'},
'7/37': { 'desc' : 'Temperature sensor, EGR'},
'7/43': { 'desc' : 'Thermostat, left seat'},
'7/44': { 'desc' : 'Thermostat, right seat'},
'7/47': { 'desc' : 'PTC resistor, pre-heater'},
'7/50': { 'desc' : 'A/C pressure sensor'},
'7/53': { 'desc' : 'Pressostat, A/C'}
};